<a href="https://colab.research.google.com/github/Daksaweaomegg10/AI_ML/blob/main/Projects/Project_18_Movie_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# loading the data from the csv file to apandas dataframe
movies_data = pd.read_csv('/content/IMDB-Movie-Dataset-with-Keywords.csv')
# printing the first 5 rows of the dataframe
movies_data.head()

index    movie_id                       movie_name  year  \
0      0  tt15354916                            Jawan  2023   
1      1  tt15748830                       Jaane Jaan  2023   
2      2  tt11663228                           Jailer  2023   
3      3  tt14993250  Rocky Aur Rani Kii Prem Kahaani  2023   
4      4  tt15732324                            OMG 2  2023   

                   genre                                           overview  \
0       Action, Thriller  A high-octane action thriller which outlines t...   
1  Crime, Drama, Mystery  A single mother and her daughter who commit a ...   
2  Action, Comedy, Crime  A retired jailer goes on a manhunt to find his...   
3  Comedy, Drama, Family  Flamboyant Punjabi Rocky and intellectual Beng...   
4          Comedy, Drama  An unhappy civilian asks the court to mandate ...   

            director                                               cast  \
0              Atlee  Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ...   
1        Sujoy Ghosh  Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ...   
2  Nelson Dilipkumar  Rajinikanth, Mohanlal, Shivarajkumar, Jackie S...   
3        Karan Johar  Ranveer Singh, Alia Bhatt, Dharmendra, Shabana...   
4           Amit Rai  Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa...   

                                             keyword  
0  thriller, Thriller, outlines, high-octane, Nay...  
1  single, Crime, Mystery, crime, Kareena Kapoor,...  
2  retired, Crime, successfully?, killers., Nelso...  
3  facing, family, their, rocky, flamboyant, afte...  
4  Pankaj Tripathi, mandate, comprehensive, unhap...

In [ ]:
# selecting the relevant features for recommendation
selected_features = ['genre','keyword','overview','cast','director']
print(selected_features)

['genre', 'keyword', 'overview', 'cast', 'director']


In [ ]:
# chceking for null values
movies_data.isnull().sum()

index          0
movie_id       0
movie_name     0
year          65
genre          0
overview       0
director       0
cast           0
keyword        0
dtype: int64

In [ ]:
# replacing the null valuess with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [ ]:
movies_data.isnull().sum()

index          0
movie_id       0
movie_name     0
year          65
genre          0
overview       0
director       0
cast           0
keyword        0
dtype: int64

In [ ]:
# combining all the 5 selected features
combined_features = movies_data['genre']+' '+movies_data['keyword']+' '+movies_data['overview']+' '+movies_data['cast']+' '+movies_data['director']
print(combined_features)

0       Action, Thriller thriller, Thriller, outlines,...
1       Crime, Drama, Mystery single, Crime, Mystery, ...
2       Action, Comedy, Crime retired, Crime, successf...
3       Comedy, Drama, Family facing, family, their, r...
4       Comedy, Drama Pankaj Tripathi, mandate, compre...
                              ...                        
2194    Thriller Thriller, Shatrughan Sinha, Subhash, ...
2195    Drama, Musical, Romance renowned, overshadow, ...
2196    Musical, Romance tournament, dancer's, Musical...
2197    Drama, Family, Fantasy after, neelam, saheb, t...
2198    Action, Comedy, Drama fearful, divorce,, Govin...
Length: 2199, dtype: object


In [ ]:
# converting text data to geature vectors
vectorizer = TfidfVectorizer()

In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)
print(feature_vectors)

  (0, 269)	0.13225620117235462
  (0, 10385)	0.2435026258865845
  (0, 7169)	0.3494757531426403
  (0, 4453)	0.2535279294065427
  (0, 7051)	0.3494757531426403
  (0, 6842)	0.28379609779930953
  (0, 9140)	0.15273732330537276
  (0, 8640)	0.19485007464631082
  (0, 5451)	0.1133568013567344
  (0, 9564)	0.24096550448905776
  (0, 5191)	0.1906305994526956
  (0, 11340)	0.33177000966735837
  (0, 11224)	0.18324741883459564
  (0, 3278)	0.2750332627592314
  (0, 10329)	0.09792763404929887
  (0, 7057)	0.03651613335130583
  (0, 6118)	0.06949248409174619
  (0, 11232)	0.0563866297233423
  (0, 4933)	0.04683653604343848
  (0, 9098)	0.09806725621654426
  (0, 10449)	0.03436984386781609
  (0, 8247)	0.16588500483367918
  (0, 4719)	0.03951233640203532
  (0, 11002)	0.08846694192056463
  (0, 9103)	0.14738521500815235
  :	:
  (2198, 2856)	0.09461997157578642
  (2198, 5467)	0.08897393447265871
  (2198, 5741)	0.11354674213397978
  (2198, 5543)	0.11264626049746339
  (2198, 5816)	0.1435603479961895
  (2198, 1227)	0.19901

In [ ]:
# to see similarity value
similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.01470161 0.01560187 ... 0.00173687 0.01297531 0.01306605]
 [0.01470161 1.         0.02205354 ... 0.0103757  0.02913068 0.00307504]
 [0.01560187 0.02205354 1.         ... 0.00147973 0.02105828 0.04844729]
 ...
 [0.00173687 0.0103757  0.00147973 ... 1.         0.01005899 0.00979012]
 [0.01297531 0.02913068 0.02105828 ... 0.01005899 1.         0.04411354]
 [0.01306605 0.00307504 0.04844729 ... 0.00979012 0.04411354 1.        ]]


In [ ]:
print(similarity.shape)

(2199, 2199)


In [ ]:
# getting the movie name from user
movie_name = input('Enter movie name : ')

Enter movie name : Jawan


In [ ]:
# creating a list with all the movie names given in the dataset
list_of_all_titles = movies_data['movie_name'].astype(str).tolist()
print(list_of_all_titles)

['Jawan', 'Jaane Jaan', 'Jailer', 'Rocky Aur Rani Kii Prem Kahaani', 'OMG 2', 'Sukhee', 'The Great Indian Family', 'The BFG', 'Pathaan', 'Mastaney', '3 Idiots', 'Satyaprem Ki Katha', 'Lion', 'Bholaa Shankar', 'Haddi', 'Friday Night Plan', 'Neeyat', 'Gadar 2', 'Por Thozhil', 'Life of Pi', 'Asoka', 'The Darjeeling Limited', 'Dangal', 'Tumbbad', 'Dunki', 'Sirf Ek Bandaa Kaafi Hai', 'Gangs of Wasseypur', 'Khufiya', 'Animal', 'Miss Shetty Mr Polishetty', 'Bawaal', 'Brahmastra Part One: Shiva', 'Ghoomer', 'Tiger 3', 'Tu Jhoothi Main Makkaar', 'Drishyam 2', 'Gandhi', 'PK', 'My Name Is Khan', 'Raees', 'Rama Banam', 'Andhadhun', 'Thank You for Coming', 'Dream Girl 2', 'Kushi', 'Taare Zameen Par', 'Drishyam', 'Chor Nikal Ke Bhaga', 'Gangubai Kathiawadi', 'Gaslight', 'The Buckingham Murders', 'Fighter', 'Bholaa', 'Om Shanti Om', 'Kabhi Khushi Kabhie Gham...', 'The Kerala Story', 'Vikram Vedha', 'Swades: We, the People', 'Bajrangi Bhaijaan', 'Bloody Daddy', 'The Hundred-Foot Journey', 'The Kashmir

In [ ]:
# finding the close match for the movie name given by the user
# Nice function from difflib library

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Jawan', 'Japan', 'Parwana']


In [ ]:
# finding the index of the movie with title
close_match = find_close_match[0] # Assign the first element of find_close_match to close_match
index_of_the_movie = movies_data[movies_data.movie_name == close_match]['index'].values[0]
print(index_of_the_movie)

0


In [ ]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
for i in similarity_score:
  if(i[1]>0.15):
    print(similarity_score.index(i))

0
8
253
2133


In [ ]:
# sorting the movies based on their similarity score
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(0, 1.0000000000000002), (8, 0.1624337091408211), (2133, 0.1562938707264879), (253, 0.15180896730475113), (191, 0.14710527256150907), (2059, 0.14684927762910158), (352, 0.14630526132665872), (1362, 0.1387797105953172), (73, 0.13212129096276157), (882, 0.13031701270848647), (53, 0.12529914923210722), (651, 0.12408408383318814), (1770, 0.12308091596014771), (530, 0.12033198603122876), (264, 0.11799512651432974), (1449, 0.11613910307311548), (246, 0.11331342384777464), (20, 0.113202200339441), (721, 0.11208674404012176), (98, 0.11141352886401774), (1788, 0.11139279361364221), (68, 0.10785743879694543), (589, 0.10771438016637748), (85, 0.10623056617379864), (151, 0.10580085626887403), (1285, 0.10438207965501244), (483, 0.10402148462742694), (208, 0.1037566808889485), (895, 0.10318584064232375), (1166, 0.10215615521633382), (147, 0.10211363535772179), (484, 0.10119686112475565), (565, 0.10087693779224517), (285, 0.10025977814490508), (748, 0.0999767553685559), (1711, 0.09636205188376132), 

In [ ]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index== index]['movie_name'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Jawan
2 . Pathaan
3 . Bhakta Kannappa
4 . Mumbaikar
5 . Happy New Year
6 . The Test
7 . Darbar
8 . Silsila
9 . Don 2
10 . Lost
11 . Om Shanti Om
12 . Chehre
13 . Lipstick Under My Burkha
14 . Connect
15 . Gehraiyaan
16 . Shuddh Desi Romance
17 . Uunchai
18 . Asoka
19 . The Intern
20 . Fan
21 . Baaghi: A Rebel for Love
22 . Jab Tak Hai Jaan
23 . Chhapaak
24 . Kal Ho Naa Ho
25 . Dilwale
26 . Sathyam
27 . Paheli
28 . Rab Ne Bana Di Jodi
29 . Dil Kya Kare


In [ ]:
# Input the user's favorite movie name
movie_name = input('Enter your favorite movie name: ')

# Convert the 'title' column to strings before creating the list
list_of_all_titles = movies_data['movie_name'].astype(str).tolist()

# Find the closest matches to the input movie name
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

# Check if a close match was found
if not find_close_match:
    print("Sorry, we couldn't find a movie matching your input. Please try again.")
else:
    close_match = find_close_match[0]
    print(f"Closest match found: {close_match}")

    # Get the index of the movie
    index_of_the_movie = movies_data[movies_data.movie_name == close_match]['index'].values[0]

    # Compute similarity scores
    similarity_score = list(enumerate(similarity[index_of_the_movie]))

    # Sort movies by similarity score in descending order
    sorted_similar_movies = sorted(similarity_score, key=lambda x: x[1], reverse=True)

    print('Movies suggested for you:\n')

    # Print the top 20 similar movies
    i = 1
    for movie in sorted_similar_movies:
        index = movie[0]
        title_from_index = movies_data[movies_data.index == index]['movie_name'].values[0]
        if i <= 20:
            print(i, '.', title_from_index)
            i += 1


Enter your favorite movie name: Maa beta
Closest match found: Maa Beta
Movies suggested for you:

1 . Parvarish
2 . Raavan
3 . Thanedaar
4 . Tridev
5 . Shakti
6 . Veerappan
7 . Deewaar
8 . Sholay
9 . Laawaris
10 . Mission Kashmir
11 . Naseeb
12 . Suhaag
13 . Rakhta Charitra
14 . Veergati
15 . Agneepath
16 . Anwar
17 . Bandit Queen
18 . Yudh
19 . Aaj Ka Arjun
