<a href="https://colab.research.google.com/github/Daksaweaomegg10/AI_ML/blob/main/Concepts/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#List v/s numpy time
from time import process_time

l=[i for i in range(100000)]

start_time=process_time()

l=[i+5 for i in l]
end_time=process_time();

t=end_time-start_time
print(t)

0.008204709999999338


In [ ]:
import numpy as np

In [ ]:
#Numpy array
np_arr=np.array([i for i in range(100000)])
start_time=process_time()

np_arr=[i+5 for i in l]
end_time=process_time();

t=end_time-start_time
print(t)


0.0069039839999991415


Numpy Array

In [ ]:
#list
l=[1,2,3,4,5]
print(l)
type(l)

[1, 2, 3, 4, 5]


list

In [ ]:
nparr=np.array([1,2,3,4,5])
print(nparr)
type(nparr)# not seprated by commass see output
# Also see the "type" output as Nd Array

[1 2 3 4 5]


numpy.ndarray

In [ ]:
_2d_np_arr=np.array([(1,2,3,4,5),(3,4,5,6,7)],dtype=float)
print(_2d_np_arr)
type(_2d_np_arr)
_2d_np_arr.shape # return the row and column

[[1. 2. 3. 4. 5.]
 [3. 4. 5. 6. 7.]]


(2, 5)

Initail Place Holders

In [ ]:
# creating 2d array of specified row and columns

x=np.zeros((3,5))# all '0'
print(x)

print("")

y=np.ones((2,4))# all '1'
print(y)

print("")

z=np.full((5,4),5)# all '5' or any value specified
print(z)

print("")

p=np.eye((5))# Identity Matrix
print(p)

print("")

q=np.random.random((3,4))# random values between 0 and 1 as default oin python
print(q)

print("")


r=np.random.randint(1,100,(3,4))# random values between 1 and 100
print(r)



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[0.6933759  0.39911722 0.36842659 0.0676397 ]
 [0.68554985 0.76774324 0.32046406 0.52245502]
 [0.77087502 0.08014285 0.78936952 0.57979755]]

[[54  5 59 59]
 [29  9 28 74]
 [22 64 76 89]]


In [ ]:
d=np.linspace(10,30,6)
print(d)

print(" ")

e=np.arange(10,35,5)
print(e)

[10. 14. 18. 22. 26. 30.]
 
[10 15 20 25 30]


In [ ]:
l=[1,2,3,4,5,6,7,8]

np=np.asarray(l)
print(np)

[1 2 3 4 5 6 7 8]


Analysing a numpy array

In [ ]:
w=np.random.randint(1,100,(4,5))
print(w.shape)# checking dimension

print(w.ndim)# checking number of dimnesion

print(w.size)# checking number of elements

print(w.dtype)# checking datatype 64 bit integer Value

(4, 5)
2
20
int64


Mathematical Operations

In [ ]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]

print(l1+l2)# Concataion occurs

np1=np.random.randint(1,10,(3,3))
np2=np.random.randint(10,20,(3,3))

print(np1+np2)# Addition Occurs
print(np.add(np1,np2))

print(np1-np2)# sub Occurs
print(np.suntract(np1,np2))

print(np1*np2)# multiply Occurs
print(np.multiply(np1,np2))

print(np1/np2)# division Occurs
print(np.division(np1,np2))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[18 22 28]
 [25 13 21]
 [25 18 18]]
[[-10  -8 -10]
 [ -7  -9 -13]
 [ -9 -14  -4]]
[[ 56 105 171]
 [144  22  68]
 [136  32  77]]
[[0.28571429 0.46666667 0.47368421]
 [0.5625     0.18181818 0.23529412]
 [0.47058824 0.125      0.63636364]]


Array Manipulation

In [ ]:
p=np.random.randint(1,10,(3,4))
# 1st Way
transpose=np.transpose(p)
print(p)
print(transpose)
print(transpose.shape)

# 2nd way
tran2=p.T
print(tran2)
print(tran2.shape)

[[4 2 2 8]
 [3 9 2 4]
 [8 7 5 1]]
[[4 3 8]
 [2 9 7]
 [2 2 5]
 [8 4 1]]
(4, 3)
[[4 3 8]
 [2 9 7]
 [2 2 5]
 [8 4 1]]
(4, 3)


In [ ]:
p=np.random.randint(1,10,(3,4))
b=p.reshape(4,3)
print(p)

[[5 7 7 5]
 [8 4 9 9]
 [5 8 9 9]]
